"""Add user location fields

Revision ID: 9626f79e0f52
Revises: 0e48450f3a9a
Create Date: 2025-02-20 04:59:36.503427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9626f79e0f52'
down_revision: Union[str, None] = '0e48450f3a9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'longitude')
    op.drop_column('users', 'latitude')
    # ### end Alembic commands ###
